// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Board struct {
	ID          string         `json:"id"`
	ProjectName string         `json:"project_name"`
	Picture     sql.NullString `json:"picture"`
	OwnerID     string         `json:"owner_id"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Comment struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TaskID    string    `json:"task_id"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type Member struct {
	UserID  string `json:"user_id"`
	BoardID string `json:"board_id"`
}

type Task struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Order     int32          `json:"order"`
	Tag       sql.NullString `json:"tag"`
	Assignee  string         `json:"assignee"`
	BoardID   string         `json:"board_id"`
	StatusID  string         `json:"status_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type TaskStatus struct {
	ID      string `json:"id"`
	Order   int32  `json:"order"`
	Name    string `json:"name"`
	BoardID string `json:"board_id"`
}

type User struct {
	ID         string         `json:"id"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
	Email      string         `json:"email"`
	Picture    sql.NullString `json:"picture"`
	Locale     string         `json:"locale"`
	BoardLimit int32          `json:"board_limit"`
	CreatedAt  time.Time      `json:"created_at"`
}
