// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBoardByOwnerID(ctx context.Context, ownerID string) (Board, error)
	GetUser(ctx context.Context, id string) (User, error)
	InitTaskStatus(ctx context.Context, arg InitTaskStatusParams) ([]TaskStatus, error)
}

var _ Querier = (*Queries)(nil)
